<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-U9HPVFIS" name="Default test" tests="2" failures="1" timestamp="9 Jan 2016 00:02:35 GMT" time="0.375" errors="0">
  <testcase name="testMergeOperation" time="0.273" classname="classyman.algorithmsintro.sorting.TestMergeSort"/>
  <testcase name="testMergeSort" time="0.041" classname="classyman.algorithmsintro.sorting.TestMergeSort">
    <failure type="java.lang.AssertionError" message="
Expecting:
  &amp;lt;[1, 2, 2, 2, 4, 5, 6]&amp;gt;
to contain exactly (and in same order):
  &amp;lt;[1, 2, 3, 4, 5, 5, 6]&amp;gt;
but could not find the following elements:
  &amp;lt;[3]&amp;gt;
">
      <![CDATA[java.lang.AssertionError: 
Expecting:
  <[1, 2, 2, 2, 4, 5, 6]>
to contain exactly (and in same order):
  <[1, 2, 3, 4, 5, 5, 6]>
but could not find the following elements:
  <[3]>

	at classyman.algorithmsintro.sorting.TestMergeSort.testMergeSort(TestMergeSort.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:207)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:178)
]]>
    </failure>
  </testcase> <!-- testMergeSort -->
</testsuite> <!-- Default test -->
